CREATE FUNCTION [dbo].[Convert_SS_To_HHMMSS_108] (
	@segundos BIGINT = 0
)

RETURNS VARCHAR(20)

BEGIN
	DECLARE @HORA_RET										VARCHAR(20) = '';
	DECLARE @DT_HORA										VARCHAR(20) = '';
	DECLARE @AUX_INT										BIGINT = 0;

	SELECT @AUX_INT = CONVERT(INT, (@segundos / 60 / 60));

	IF(@AUX_INT < 10)BEGIN
		SET @DT_HORA = '0' + CONVERT(VARCHAR(2), @AUX_INT);
	END ELSE BEGIN
		SET @DT_HORA = CONVERT(VARCHAR(2), @AUX_INT);
	END;
				
	SELECT @AUX_INT = CONVERT(INT, (@segundos / 60 % 60));
	IF(@AUX_INT < 10)BEGIN
		SET @DT_HORA += ':0' + CONVERT(VARCHAR(2), @AUX_INT);
	END ELSE BEGIN
		SET @DT_HORA += ':' + CONVERT(VARCHAR(2), @AUX_INT);
	END;

	SELECT @AUX_INT = CONVERT(INT, (@segundos % 60));
	IF(@AUX_INT < 10)BEGIN
		SET @DT_HORA += ':0' + CONVERT(VARCHAR(2), @AUX_INT);
	END ELSE BEGIN
		SET @DT_HORA += ':' + CONVERT(VARCHAR(2), @AUX_INT);
	END;

   SET @HORA_RET = ISNULL(CONVERT(VARCHAR(20), @DT_HORA, 108), '')	

RETURN @HORA_RET;

END;